image: node:12-alpine

cache: &global_cache
  policy: pull
  paths:
    - node_modules

before_script:
  - yarn install

pages:
  only:
    - master
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - yarn docs
  artifacts:
    paths:
      - public

lint:
  stage: test
  needs: []
  script:
    - yarn lint --color

publish-next:
  only:
    - master
  needs:
    - lint
  stage: deploy
  script:
    - echo "//gitlab.com/api/v4/projects/18148878/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish --no-git-tag-version --tag next

publish-latest:
  only:
    refs:
      - tags
  needs:
    - lint
  stage: deploy
  script:
    - echo "//gitlab.com/api/v4/projects/18148878/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish --no-git-tag-version
